
    import React from 'react';
    import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
    import { DollarSign, Users, ShoppingCart, TrendingUp } from 'lucide-react';
    import { motion } from 'framer-motion';

    // Simple placeholder for a bar chart bar
    const ChartBar = ({ value, maxValue, label, colorClass = 'bg-primary' }) => {
      const heightPercentage = maxValue > 0 ? (value / maxValue) * 100 : 0;
      return (
        <div className="flex flex-col items-center space-y-1">
          <div className="w-10 h-40 bg-muted rounded flex items-end">
            <motion.div
              className={`w-full rounded ${colorClass}`}
              initial={{ height: 0 }}
              animate={{ height: `${heightPercentage}%` }}
              transition={{ duration: 0.5, ease: "easeOut" }}
            />
          </div>
          <span className="text-xs text-muted-foreground">{label}</span>
        </div>
      );
    };

    const AdminAnalytics = () => {
      // Fictional data for admin analytics
      const monthlyRevenue = [
        { label: 'Jan', value: 15000 }, { label: 'Feb', value: 18000 },
        { label: 'Mar', value: 22000 }, { label: 'Apr', value: 20000 },
        { label: 'May', value: 28000 }, { label: 'Jun', value: 32000 },
      ];
      const maxRevenue = Math.max(...monthlyRevenue.map(d => d.value), 0);

      const commissionData = [
        { label: 'Jan', value: 1500 }, { label: 'Feb', value: 1800 },
        { label: 'Mar', value: 2200 }, { label: 'Apr', value: 2000 },
        { label: 'May', value: 2800 }, { label: 'Jun', value: 3200 },
      ];
      const maxCommission = Math.max(...commissionData.map(d => d.value), 0);

      return (
        <div className="space-y-6">
          {/* Key Metrics */}
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
            <Card className="glassmorphism">
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Site Revenue</CardTitle>
                <DollarSign className="h-5 w-5 text-green-500" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">$135,000.00</div>
                <p className="text-xs text-muted-foreground">+20.1% from last month</p>
              </CardContent>
            </Card>
            <Card className="glassmorphism">
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Commissions Earned</CardTitle>
                <TrendingUp className="h-5 w-5 text-blue-500" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">$13,500.00</div>
                <p className="text-xs text-muted-foreground">+18.5% from last month</p>
              </CardContent>
            </Card>
            <Card className="glassmorphism">
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Active Users</CardTitle>
                <Users className="h-5 w-5 text-purple-500" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">1,250</div>
                <p className="text-xs text-muted-foreground">+50 new users this week</p>
              </CardContent>
            </Card>
            <Card className="glassmorphism">
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Transactions</CardTitle>
                <ShoppingCart className="h-5 w-5 text-orange-500" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">5,820</div>
                <p className="text-xs text-muted-foreground">+300 this month</p>
              </CardContent>
            </Card>
          </div>

          {/* Charts */}
          <div className="grid gap-6 md:grid-cols-2">
            <Card className="glassmorphism">
              <CardHeader>
                <CardTitle>Monthly Site Revenue</CardTitle>
                <CardDescription>Total revenue generated by the platform per month.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-around items-end h-56 p-4">
                  {monthlyRevenue.map((data) => (
                    <ChartBar key={data.label} value={data.value} maxValue={maxRevenue} label={data.label} colorClass="bg-green-500" />
                  ))}
                </div>
              </CardContent>
            </Card>

            <Card className="glassmorphism">
              <CardHeader>
                <CardTitle>Monthly Commissions Earned</CardTitle>
                <CardDescription>Total commissions earned by the platform per month.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-around items-end h-56 p-4">
                  {commissionData.map((data) => (
                    <ChartBar key={data.label} value={data.value} maxValue={maxCommission} label={data.label} colorClass="bg-blue-500" />
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

           <Card className="glassmorphism">
              <CardHeader>
                <CardTitle>Logistics Overview</CardTitle>
                <CardDescription>Key insights into platform logistics (fictional).</CardDescription>
              </CardHeader>
              <CardContent className="grid md:grid-cols-3 gap-4">
                  <div className="p-4 border rounded-lg">
                      <h4 className="font-semibold text-lg">Average Shipping Time</h4>
                      <p className="text-2xl font-bold text-primary">3.5 Days</p>
                      <p className="text-xs text-muted-foreground">Based on last 100 orders</p>
                  </div>
                  <div className="p-4 border rounded-lg">
                      <h4 className="font-semibold text-lg">Distribution Centers Active</h4>
                      <p className="text-2xl font-bold text-primary">5 / 5</p>
                      <p className="text-xs text-muted-foreground">All centers operational</p>
                  </div>
                  <div className="p-4 border rounded-lg">
                      <h4 className="font-semibold text-lg">Return Rate</h4>
                      <p className="text-2xl font-bold text-destructive">2.1%</p>
                      <p className="text-xs text-muted-foreground">Slightly below average</p>
                  </div>
              </CardContent>
            </Card>
        </div>
      );
    };

    export default AdminAnalytics;
  